# General game settings.
game:
  language: english

  # Enable all script functions.
  scripting: true

  # If specified, this level will be loaded instead of normal game.
  debugLevel:

  # Enable debug mode.
  debug: false

  # Physics.
  gravity: -9.81
  particleRadius: 0.05
  maxParticles: 5000

# Video settings.
video:
  screen:
    fullscreen: false
    width: 800
    height: 600
  fpsLimit: 60
  vsync: true