# General game settings.
game:
  language: english

  # Enable all script functions.
  scripting: false

  # If specified, this level will be loaded instead of normal game.
  debugLevel: test

  # Enable debug mode.
  debug: true

  # Physics.
  gravity: -9.81
  particleRadius: 0.1

# Video settings.
video:
  screen:
    fullscreen: false
    width: 800
    height: 600
  fpsLimit: 60
  vsync: true