# General game settings.
game:

  # Enable all script functions.
  scripting: false

  # Enable debug mode.
  uiDebug: true
  debug: true

  # Physics.
  gravity: -9.81
  particleRadius: 0.1

# Video settings.
video:
  screen:
    fullscreen: false
    width: 1200
    height: 800
  fpsLimit: 100