# General game settings.
game:
  language: english

  # Enable all script functions.
  scripting: true

  # If specified, this level will be loaded instead of normal game.
  debugLevel:

  # Enable debug mode.
  debug: false

  # Physics.
  gravity: -9.81
  particleRadius: 0.05
  maxParticles: 5000

  # Other.
  soundVolume: 0.6
  musicVolume: 0.05

# Video settings.
video:
  screen:
    fullscreen: false
    width: 800
    height: 600
  fpsLimit: 60
  vsync: true

# Input settings.
input:
  up: W
  down: S
  left: A
  right: D
  shrink: E
  stick: Space
  reset: R